language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_deploy: |
  node -e 'require("fs").writeFileSync("package.json", JSON.stringify(Object.assign(require("./package"), {version: process.env.TRAVIS_TAG})))'
deploy:
  provider: npm
  skip_cleanup: true
   on:
    tags: true
